# Generated by Django 6.1.1 on 2026-09-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0013_contact_is_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="preferred_communication_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PHONE", "Phone"),
                    ("EMAIL", "Email"),
                    ("SMS", "SMS"),
                    ("WHATSAPP", "WhatsApp"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CALL", "Call"),
                    ("EMAIL", "Email"),
                    ("EXISTING CUSTOMER", "Existing Customer"),
                    ("PARTNER", "Partner"),
                    ("PUBLIC RELATIONS", "Public Relations"),
                    ("CAMPAIGN", "Campaign"),
                    ("WEBSITE", "Website"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEAD", "Lead"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("QUALIFIED", "Qualified"),
                    ("NOT_QUALIFIED", "Not Qualified"),
                    ("LOST", "Lost"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Last name"
            ),
        ),
    ]
