# Generated by Django 6.1.1 on 2026-09-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0014_contact_preferred_communication_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="preferred_communication_channel",
            field=models.CharField(
                blank=True,
                choices=[("SMS", "SMS"), ("CALL", "Call"), ("EMAIL", "Email")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google"),
                    ("TIKTOK", "TikTok"),
                    ("ORGANIC", "Organic"),
                    ("CALL", "Call"),
                    ("CUSTOMER_REFERAL", "Customer Referal"),
                    ("EMPLOYER_REFERAL", "Employer Referal"),
                    ("WALK_IN", "Walk In"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
