# Generated by Django 6.1.1 on 2026-09-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0015_alter_contact_preferred_communication_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="stage_entered_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
